services:
  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - path : ".env"
        required: true
    command: redis-server --save 20 1 --loglevel warning --requirepass $DB_PASSWORD
    volumes:
      - ./data:/data
